description: "Ura is the design studio dedicated to making open source software more usable, accessible and competitive."
evaluations: "The following are UX evaluations performed by Ura Design team and collaborators."
website: "https://ura.design"
contact: "https://ura.design/contact"
debug: false
templates:
  light:
    background: "#dddddd"
    color: "#000000"
  dark:
    background: "#111111"
    color: "#ffffff"

reveal:
  history: true
  slide_number: false
  transition: "slide"
  transition_speed: "fast"
  center: true
  disableLayout: false
  controls: false
  theme: "ux-evaluation"
  templates:
    blue:
      background: "#0011DD"
      color: "#ffffff"
    light:
      background: "#dddddd"
      color: "#000000"
    dark:
      background: "#111111"
      color: "#ffffff"

headless_cms:
  engine: "decap"
  site_url: "https://evaluations.ura.design/"
  display_url: "https://evaluations.ura.design/"
  logo_url: "https://evaluations.ura.design/logo.svg"
  media_folder: "static/uploads"
  public_folder: "/uploads"
  backend:
    name: "github"
    repo: "uradotdesign/evaluations"
  branch: "main"
  squash_merges: false
  collections:
    evaluation:
      name: "evaluations"
      label: "Evaluations"
      folder: "content"
      create: true
      widget: "list"
      create: true
      editor:
        preview: true
      fields:
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Publish Date"
          name: "date"
          widget: "datetime"
    
        - label: "Project Website"
          name: "website"
          widget: "string"

        - label: "Author"
          name: "author"
          widget: "string"
          
        - label: "Author URL"
          name: "author_url"
          widget: "string"
          
        - label: "Author Contact"
          name: "author_contact"
          widget: "string"
          
        - label: "Devices"
          name: "devices"
          widget: "list"
          
        - label: "Environments"
          name: "environments"
          widget: "list"
          
        - label: "Focus Areas"
          name: "focus_areas"
          widget: "list"
          
        - label: "Goals"
          name: "goals"
          widget: "string"
          
        - label: "Findings"
          name: "findings"
          widget: "markdown"
          
        - label: "Closing"
          name: "closing"
          widget: "markdown"

      nested:
        depth: 1000
